
services:
  api:
    image: ghcr.io/willhensel/adsbmon/api:main
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ASPNETCORE_HTTP_PORTS: 5000
      DUMP1090_IP_ADDR: <address>
      DUMP1090_PORT: <port>
    ports:
      - 5000:5000