name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build API Docker image
      run: docker build . --file ./AdsbMon.Api/Dockerfile --tag willhensel/adsbmon/api:$(date +%s)
